import type { Site } from './types';
import { db } from './sqlite';

const pilot: Site = { id: 'pilot-jnvckm', tenantId: 'jnvckm', label: 'JNVCKM Alumni Association', repo: 'hamb1y/jnvckm', branch: 'main', provider: 'github', apiRoot: 'http://localhost:5173/gh/hamb1y/jnvckm', allowedOrigins: ['http://localhost:5173'], credentialRef: 'development-token', enabled: true, settings: {} };
const sites = new Map<string, Site>([[pilot.repo, pilot]]);
function fromRow(row: Record<string, unknown>): Site { return { id: String(row.id), tenantId: String(row.tenant_id), label: String(row.label), repo: String(row.repo), branch: String(row.branch), provider: row.provider as Site['provider'], apiRoot: String(row.api_root), allowedOrigins: JSON.parse(String(row.allowed_origins ?? '[]')), credentialRef: row.credential_ref ? String(row.credential_ref) : null, enabled: Boolean(row.enabled), settings: JSON.parse(String(row.settings ?? '{}')) }; }
export function resolveSite(apiRoot: string): Site | undefined { return [...sites.values()].find((site) => site.apiRoot === apiRoot); }
export function resolveSiteFromPath(pathname: string): Site | undefined { const match = pathname.match(/^\/gh\/([^/]+)\/([^/]+)(?:\/|$)/); return match ? sites.get(`${match[1]}/${match[2]}`) : undefined; }
export async function resolveSiteFromPathAsync(pathname: string): Promise<Site | undefined> { const match = pathname.match(/^\/gh\/([^/]+)\/([^/]+)(?:\/|$)/); if (!match) return undefined; const repo = `${match[1]}/${match[2]}`; if (!process.env.TURSO_DATABASE_URL) return sites.get(repo); try { const result = await db.query<Record<string, unknown>>('SELECT * FROM sites WHERE repo = ? AND enabled = 1 LIMIT 1', [repo]); const site = result.rows[0] ? fromRow(result.rows[0]) : undefined; if (site) sites.set(repo, site); return site; } catch { return sites.get(repo); } }
export async function listSites(): Promise<Site[]> { if (!process.env.TURSO_DATABASE_URL) return [...sites.values()]; try { const result = await db.query<Record<string, unknown>>('SELECT * FROM sites ORDER BY label'); const loaded = result.rows.map(fromRow); loaded.forEach((site) => sites.set(site.repo, site)); return loaded.length ? loaded : [...sites.values()]; } catch { return [...sites.values()]; } }
export async function addSite(site: Site): Promise<void> { registerSite(site); if (process.env.TURSO_DATABASE_URL) await db.query('INSERT INTO sites (id, tenant_id, label, repo, branch, provider, api_root, allowed_origins, credential_ref, enabled, settings) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [site.id, site.tenantId, site.label, site.repo, site.branch, site.provider, site.apiRoot, JSON.stringify(site.allowedOrigins), site.credentialRef, site.enabled ? 1 : 0, JSON.stringify(site.settings)]); }
export function registerSite(site: Site): void { sites.set(site.repo, site); }
